apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0     # zero-downtime deploys
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      # credentials to pull from the PRIVATE Harbor registry
      imagePullSecrets:
        - name: harbor-creds
      containers:
        - name: demo-app
          # This line is rewritten by the CI pipeline on every deploy.
          image: harbor.harbor.svc.cluster.local:80/intern-demo/demo-app:4d88d78ac6c77ecca8d3ad309f525f001226bf0c
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "1.0.0"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
