---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-creds
  namespace: demo
spec:
  encryptedData:
    .dockerconfigjson: AgAFvq+0O4WJ0k0ed4n0K5yrXsdOO6MW1qlLnfUAwDA2fTAqXx6Gigyj2j4uXVvZxkTCsYqY7ZhawXHon2nkW4H99T9rQ2fwWJh6SroNf42+/bkk/WJncL+IxnduPidZosZt7siU33SeKBa/mtWatq3J7JLvRfuuafi/h8ExLC7OBdRtENoeD4EISO2vtW9U/E8BsJQft/ijSbO+X0oHIWU33IZYCzXNmQBdrFqtDpcCTaFJ7wIHMm2cfuLblBV6cg2FAHxiEooE7is0SkUplzgB9qGGV2w/WgyAWu333G8l739aKvro9hDrbLmywL3U79xa1Jj9r1PumQSSvM/nSXC+2XQQdAzN/IBXJezjYsr1Pkjm/+JVrg0hgM908lTps7ZTvcLbEo5rEnbjOFOa8LTkPDmN40h8Pd+qpPqDgFXl9ede2vXKv9Sg4aEoDmRERTapMYvUqubM70CkAdjQtxBgs5fdyfIJfATLSPs+PdT5IQfCsLhEMK8giiNM7sYn2gQgpoj+kxEnDmrsXQnvGqWBSuTF+81C4zpiggMrFof67QnFUelMy0pAN7f2/HvLnO/zmQSlWt0ecLhlEzZQvTav610Q9bjXacssTHGSyuBEnK0wYgRg93DpQ2lh5HIOKpBP+BH3eAHHxuLVey2zbnLHNGCsWOJk0VB+O3XmHsP1ww/VTrfiNcS/Src3rXdiMMhI7seZO+LLxDEvQpMhYDPoQuDiEQdh8ejTIk0Zx5s2ATL61UvDYrb0TBX7JkWA7G9lqAD7YmD058g7M11cNY4r4Q4qSL6TXCObb4IfxQS27fz0bEizmAjeF7fPuuk4TagoMrox7hduRChFTPPZC1Eo9GukatoCg6EYhiDrZiwnOEcedaezrA49wJtlD3um8sFQfXWx8TQG4j5VMqEPqh0n3k0cROkkugZY3hYg9UpDLFPsc7llJ94i1jotElphyFxBPCtxAyWHeIxEeNRrEkIoXmsetA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-creds
      namespace: demo
    type: kubernetes.io/dockerconfigjson
