---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-creds
  namespace: demo
spec:
  encryptedData:
    .dockerconfigjson: AgAwNIEybrigmK1iaU9UXgx8KkwyOaM73+8vzuT5Dwe/NolOF/UrCZy811Yb+o5I7SV3NBB2pR70FxfKampQW0ccTqzEiy5KcBSrIfGkIaQ1K7pr2Xak1vTWb1QLvYcxIZeNQhSUjzcwGCU6gvXdLNSaKpHOgqt9i6eEp6HIUYL1z977rU/YOdokZj10fr6BAfTodx9324LI+cp11Hc7q79tUxGCulma67UXLeEdWCTa1uB+FzMyCbjLOTnP/B05upBJ+0G59MBPz3qN924FWlScTu7Ew5gVtDWyHlvr4pT2kQ4UWErlo4ksmAUlMxpwl1WJPBANJ/QFKAlWvKVxc/ngO87Ks6ALjGkH3I0uw2U2ZZxR1TtjNtBzEUyVDMg/Afu0iGHFLocLGDrxL8FEfDTm+ERzv6AGLNsHHgwQsc4ZHtnl2NJ8jCbpeq4HBQTRZbccuNWwzswd2MzGPKZvzDuO/6c9gONREH1h8cKfE+8nJ+3l6vXFqZtu3Aab/vsSKS6T8NUDip/WR5q4ZQ+96fNQcEzZYyLO1wcJedRBz7jQe6GGicqcZ0PgyULj40XrIHy8IVPgLWw/ECrG+p06Rst/VzspSfb7pdWf9GyiZbwxii3ludxOB3tv7VCbiwA+WOqdipK9e9Ncvnk97udkx9bEMtzp6hD5+qawFIseoybryZDt+053+5twdSB1z1/BCSGK4N7Qa3OA2Y5l0W5TmRLALEBjzX1tQXG5ujN8mdSLsIO7k7BRRmFH2h2YIV5BrTRQ/Y6OF4XlgPigsTihe/YXrlY9vBg7GUtD3Axz0PFHlw5pCdDvU6fWG1mNc7AFidXhyKD8bot0Os+YUSUf68zz3ZZzytCJigxxvXB7Xe4PhbndZLggX1NneevpuIIUCxr8qlWJI9T0qBMNCnmKRY3CvqDLLxGcIxoBfiRuKKP6GtM4Zl4uxwJg7kFtkqnHgqtnma6bHMtOoEF6TcjRLpkqK4nqsQ==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-creds
      namespace: demo
    type: kubernetes.io/dockerconfigjson
