---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-creds
  namespace: demo
spec:
  encryptedData:
    .dockerconfigjson: AgAhc6wQMAbcf3rTUzKn9zOL2UghFWaw1yBoKIv8IU7TaQKz2iY3u6BLobJOtH/reax7xd/1szqlxm9lonvc9n3h3Uf6V+TiNs3pVzcSfOh0OOy+tdxODmeEptJ7mhUtz0G33chPLh/9kv/4x5hC1HZSibGscGszkf+kNBtQY/bDoL4t4j7hwJhWIWU2Q4NPPpEOJAtN7QLRx4BsKTGIopfW0SUGNGN/8NGPP9zw7piE8zWXwQ17jr7lUM57GoXQ2/rP84wypvARiKbIKi0RWpgkI2yXRCwNnu3KQzvR21oPnN9H5lLTJ15nuamTePZbk/oLSAZBojJdNXbutkktaZaOMrFMzkpN2YeC6pP7Fv6oq3coZmhskWbYdbQMbaBdostQ03gha3cRK7hqraRLHtU86qTG0b2GMUUGvCx2Z+MJ2sPc3pkmMfR/BncczFGinjvImF+jRon+dtY55C67gPHS7Fg5/bG+RFOMV+WG9hR1w6IdMTFxYZo+PkMIXXxU7Dj6zbKn8xopq5L+J8y/L4Hczuiqto2Tl4XvNMx0xIR/MBhhZGg+CHxduQ7C+nsm028H+E5Uc6Bm2a/pTf5psyIvmxUMUIxIvSgmEks/gV2giaPIqrI4G/+mtVspS3KX7ZdbRr1SsbL1DkwLtC4YXY3yDI6GO+bykZS4APi1FUsH+Nnc/jQHNoqMyqYljDWOF0Z+bHbMrYTDOMBXyHhDEm14ExvvAN3i4/KlFCVnYi/4xOr4J/4J9aX9N/ZSmpXmubFkip8JyoYZpNfmJqreHJaCjqgH+TpcVq7mRhH5xiP5QvO5HdAnGG3w2SN1bZeyeE3CRwxg+t4G0fwjVP22T/kTR/mvD40pr9rCTXDi9OvQfGln6R/SvsRlBztvUd9rYZR1oWAcA+6wv1OXvRIADMJuVhki+2+V1lzz3nVU4KHmWtALejB4sbGfsSWvB2jNz840oBuNSV9B9q6ulBM8s4o2gKkphQ==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-creds
      namespace: demo
    type: kubernetes.io/dockerconfigjson
